spring.application.name=ecommerce

# Đổi port ứng dụng sang 8080
server.port=8080

# Support reading from .env file
spring.config.import=optional:file:.env[.properties],optional:file:Spring-Backend/.env[.properties]

# Database url address
spring.datasource.url = ${DATASOURCE_URL}

# Frontend URL
frontend.url=${FRONTEND_URL}

# Config user
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Driver của MySQL
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL ra console để bạn dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true