spring.application.name=ecommerce

# Đổi port ứng dụng sang 8080
server.port=8080

# Database url address
spring.datasource.url = jdbc:mysql://localhost:3306/mydb

# Config user
spring.datasource.username=root
spring.datasource.password=Thai@983110@

# Driver của MySQL
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL ra console để bạn dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true